//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppDynamicProperties) DeepCopyInto(out *AppDynamicProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppDynamicProperties.
func (in *AppDynamicProperties) DeepCopy() *AppDynamicProperties {
	if in == nil {
		return nil
	}
	out := new(AppDynamicProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgsSpec) DeepCopyInto(out *ArgsSpec) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ValueFromCRD)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgsSpec.
func (in *ArgsSpec) DeepCopy() *ArgsSpec {
	if in == nil {
		return nil
	}
	out := new(ArgsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudWatchProperties) DeepCopyInto(out *CloudWatchProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudWatchProperties.
func (in *CloudWatchProperties) DeepCopy() *CloudWatchProperties {
	if in == nil {
		return nil
	}
	out := new(CloudWatchProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataDogProperties) DeepCopyInto(out *DataDogProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataDogProperties.
func (in *DataDogProperties) DeepCopy() *DataDogProperties {
	if in == nil {
		return nil
	}
	out := new(DataDogProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataScourceSpec) DeepCopyInto(out *DataScourceSpec) {
	*out = *in
	in.Provider.DeepCopyInto(&out.Provider)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataScourceSpec.
func (in *DataScourceSpec) DeepCopy() *DataScourceSpec {
	if in == nil {
		return nil
	}
	out := new(DataScourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataSourceProvider) DeepCopyInto(out *DataSourceProvider) {
	*out = *in
	if in.CloudWatch != nil {
		in, out := &in.CloudWatch, &out.CloudWatch
		*out = new(CloudWatchProperties)
		**out = **in
	}
	if in.AppDynamics != nil {
		in, out := &in.AppDynamics, &out.AppDynamics
		*out = new(AppDynamicProperties)
		**out = **in
	}
	if in.DataDog != nil {
		in, out := &in.DataDog, &out.DataDog
		*out = new(DataDogProperties)
		**out = **in
	}
	if in.Elastic != nil {
		in, out := &in.Elastic, &out.Elastic
		*out = new(ElasticProperties)
		**out = **in
	}
	if in.Graphite != nil {
		in, out := &in.Graphite, &out.Graphite
		*out = new(GraphiteProperties)
		**out = **in
	}
	if in.GrayLog != nil {
		in, out := &in.GrayLog, &out.GrayLog
		*out = new(Graylogproperties)
		**out = **in
	}
	if in.NewRelic != nil {
		in, out := &in.NewRelic, &out.NewRelic
		*out = new(NewRelicProperties)
		**out = **in
	}
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(PrometheusProperties)
		**out = **in
	}
	if in.Splunk != nil {
		in, out := &in.Splunk, &out.Splunk
		*out = new(SplunkProperties)
		**out = **in
	}
	if in.StackDriver != nil {
		in, out := &in.StackDriver, &out.StackDriver
		*out = new(StackDriverProperties)
		**out = **in
	}
	if in.SumoLogic != nil {
		in, out := &in.SumoLogic, &out.SumoLogic
		*out = new(SumoLogicProperties)
		**out = **in
	}
	if in.VmwareTanzu != nil {
		in, out := &in.VmwareTanzu, &out.VmwareTanzu
		*out = new(VmwareTanzuProperties)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataSourceProvider.
func (in *DataSourceProvider) DeepCopy() *DataSourceProvider {
	if in == nil {
		return nil
	}
	out := new(DataSourceProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Datasource) DeepCopyInto(out *Datasource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Datasource.
func (in *Datasource) DeepCopy() *Datasource {
	if in == nil {
		return nil
	}
	out := new(Datasource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Datasource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasourceList) DeepCopyInto(out *DatasourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Datasource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasourceList.
func (in *DatasourceList) DeepCopy() *DatasourceList {
	if in == nil {
		return nil
	}
	out := new(DatasourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DatasourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasourceSpec) DeepCopyInto(out *DatasourceSpec) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]ArgsSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DataSources != nil {
		in, out := &in.DataSources, &out.DataSources
		*out = make([]DataScourceSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasourceSpec.
func (in *DatasourceSpec) DeepCopy() *DatasourceSpec {
	if in == nil {
		return nil
	}
	out := new(DatasourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticProperties) DeepCopyInto(out *ElasticProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticProperties.
func (in *ElasticProperties) DeepCopy() *ElasticProperties {
	if in == nil {
		return nil
	}
	out := new(ElasticProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GraphiteProperties) DeepCopyInto(out *GraphiteProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GraphiteProperties.
func (in *GraphiteProperties) DeepCopy() *GraphiteProperties {
	if in == nil {
		return nil
	}
	out := new(GraphiteProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Graylogproperties) DeepCopyInto(out *Graylogproperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Graylogproperties.
func (in *Graylogproperties) DeepCopy() *Graylogproperties {
	if in == nil {
		return nil
	}
	out := new(Graylogproperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NewRelicProperties) DeepCopyInto(out *NewRelicProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewRelicProperties.
func (in *NewRelicProperties) DeepCopy() *NewRelicProperties {
	if in == nil {
		return nil
	}
	out := new(NewRelicProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusProperties) DeepCopyInto(out *PrometheusProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusProperties.
func (in *PrometheusProperties) DeepCopy() *PrometheusProperties {
	if in == nil {
		return nil
	}
	out := new(PrometheusProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplunkProperties) DeepCopyInto(out *SplunkProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplunkProperties.
func (in *SplunkProperties) DeepCopy() *SplunkProperties {
	if in == nil {
		return nil
	}
	out := new(SplunkProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StackDriverProperties) DeepCopyInto(out *StackDriverProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StackDriverProperties.
func (in *StackDriverProperties) DeepCopy() *StackDriverProperties {
	if in == nil {
		return nil
	}
	out := new(StackDriverProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SumoLogicProperties) DeepCopyInto(out *SumoLogicProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SumoLogicProperties.
func (in *SumoLogicProperties) DeepCopy() *SumoLogicProperties {
	if in == nil {
		return nil
	}
	out := new(SumoLogicProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueFromCRD) DeepCopyInto(out *ValueFromCRD) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SecretRef)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueFromCRD.
func (in *ValueFromCRD) DeepCopy() *ValueFromCRD {
	if in == nil {
		return nil
	}
	out := new(ValueFromCRD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VmwareTanzuProperties) DeepCopyInto(out *VmwareTanzuProperties) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VmwareTanzuProperties.
func (in *VmwareTanzuProperties) DeepCopy() *VmwareTanzuProperties {
	if in == nil {
		return nil
	}
	out := new(VmwareTanzuProperties)
	in.DeepCopyInto(out)
	return out
}
